### ISSUE TITLE
Reduce loops

### ISSUE THREAD

**Issue by philvessey** [philvessey/NextDepartures#11]
Calculate the three days in one loop so that the timezone calculated and so on can be reused. This is likely to improve performance.

**Comment by hypervtechnics** [comment]
This will also save a lot of iterations when only wanting a specific count of results.

**Comment by philvessey** [comment]
Is this a big refactor job again?

**Comment by hypervtechnics** [comment]
No more kind of changing loop iterations and moving code and removing/adding parameters.

**Comment by philvessey** [comment]
OK great - I have got some benchmarks on how long each call takes now so I can compare.

**Comment by hypervtechnics** [comment]
Okay I will do the optimization during the next days...

**Comment by hypervtechnics** [comment]
I still have this planned and did not forget it. Very busy atm.

**Comment by philvessey** [comment]
Ok no problem :)

**Comment by hypervtechnics** [comment]
Okay, I looked into it. I'd leave it for now like it is. It's getting complicated as ByStop and ByTrip have different approaches of handling the limit. If I fully understood the logic I will do some more refactoring on the refactored part. Any thoughts @philvessey ?

**Comment by philvessey** [comment]
I'm happy to leave as it is - its already pretty fast at returning results depending on the size of the data set of course. I will close this one for now - can always be reopened if we have a change of heart.
