### ISSUE TITLE
Initial loading

### ISSUE THREAD

**Issue by hypervtechnics** [philvessey/NextDepartures#15]
Initial loading of all required data. 

Two ways:

1. Add a new parameter (`preload` or `cache`) to the load value which creates an inner cache proxy for the IDataStorage.
2. Or simply enhance the current solution. But code is not at the right place.

I prefer 1.

**Comment by philvessey** [comment]
What do we need to do to put this in place - if 1 is the best option we can go with that.

**Comment by hypervtechnics** [comment]
I'd go with 1. Will implement it now. Without changing functionality. Caching in between will be some more advanced as the query filters are applied in the sql.

**Comment by philvessey** [comment]
Is the intention being less hits on the database as the data already been preloaded / cached?

**Comment by hypervtechnics** [comment]
Yeah and in 95% of the case the data is static which may make querying via LINQ more easier for us and guarantuees.

**Comment by hypervtechnics** [comment]
Implemented and pushed. But unfortunaley the parameter list grew a lot...

**Comment by philvessey** [comment]
I don't think that's a problem as its the inner library making those calls - the end user doesn't really have to specify many parameters at all.

**Comment by philvessey** [comment]
I will do some testing tomorrow evening to make sure results are still as expected - some classes are reporting that _dataStorageProperties is never used - Feed.cs and PreloadDataStorage.cs - is that needed?

**Comment by hypervtechnics** [comment]
Yeah for the Feed.cs the private field should be left. I removed the other one.

What I don't like that much for now is that there are still calls to the provider required at the start of the GetServices methods... I will look for a better solution. Maybe in parallel with restructuring the loops.

**Comment by philvessey** [comment]
OK - I will be doing some more testing on Sunday to ensure results are as expected. If you do anymore commits before then I can test those too.

**Comment by philvessey** [comment]
Everything looks good testing wise - data returned by all the endpoints is as expected. Is work on this issue now complete or is there more work needed?

**Comment by hypervtechnics** [comment]
I will do some refactoring with the other issues. Can be closed.

**Comment by hypervtechnics** [comment]
So what's up with preloading? Also are there any other tasks?

**Comment by philvessey** [comment]
Seems ok to me - been testing the 2.0.0 version over the last couple of days and don't think there are any loading issues.
