### ISSUE TITLE
Consider removing the Get* methods in Feed class where its only delegating to the data storage

### ISSUE THREAD

**Issue by hypervtechnics** [philvessey/NextDepartures#16]

**Comment by hypervtechnics** [comment]
What do you think about this one? As the user is in charge of providing the storage he can also call the methods directly there, I think.

**Comment by philvessey** [comment]
I had a think about this - my initial thoughts are that if some endpoints, such as the services ones, still need to be called as an endpoint then to keep things simple they should all be endpoints - don't think it makes sense to have one way of calling some data and a different way of calling some other bit of data.

Unless I'm getting the wrong idea of what you are thinking?

**Comment by hypervtechnics** [comment]
You are right. Then maybe also make the feed an IDataStorage? This will ensure it has all the same capabilities as the storage + the service calculation

**Comment by philvessey** [comment]
Doesn't that mean adding in all the same methods into feed that are in the IDataStorage? Not sure what benefit that brings over the current approach?

**Comment by hypervtechnics** [comment]
Aren't they all there anyway?

**Comment by philvessey** [comment]
Changing all the:

public partial class Feed to public partial class Feed : IDataStorage

Reports errors that Feed doesn't implement interface members such as -> 'Feed' does not implement interface member 'IDataStorage.GetAgenciesAsync() unless you can see something that I'm missing.

**Comment by philvessey** [comment]
If you want to have a look your side if I'm missing something the dev branch is up to date so you can pull down the latest commits and make the changes.

**Comment by hypervtechnics** [comment]
Nevermind. Some methods are only available on the data storage. No complaints.
