### ISSUE TITLE
Real time data

### ISSUE THREAD

**Issue by philvessey** [philvessey/NextDepartures#20]
Add an option to include a url to a real time feed if there is one available to replace the scheduled times with ones from a real time source.

**Comment by philvessey** [comment]
@hypervtechnics do you think there would be a use for this - I have played with this before using the real time protocol buffer feeds that transit operators put out E.g. - http://api.bart.gov/gtfsrt/tripupdate.aspx so if there is real time info for a service show those times instead?

**Comment by philvessey** [comment]
If no url provided or no real time data for a service then carry on showing scheduled times.

**Comment by philvessey** [comment]
On doing some more research it doesn't seem that real time GTFS is very popular and a lot of those feeds are closed / behind paywalls so I will park this issue.

**Comment by hypervtechnics** [comment]
> 
> 
> If no url provided or no real time data for a service then carry on showing scheduled times.

This would be my preferred approach if it would be implemented.



> 
> 
>it doesn't seem that real time GTFS is very popular

But I agree with this, so maybe we can either abstract the whole thing away and maybe also give the user the ability to implement their own realtime service. For now I would park that issue too.

**Comment by philvessey** [comment]
Been thinking a little more about this - what do you think of the following approach:

- Separate library for realtime.
- Once you have list of services from scheduled times you can then choose to pass the list of services to the realtime library and have it update the departureTimes based on real time data.

This of course means if you don't want to use realtime or it's not available you don't have to. Any thoughts?

**Comment by philvessey** [comment]
I still don't think there is enough scope with available realtime feeds to make it viable currently so I think I will go ahead and close this one.
