### ISSUE TITLE
Decouple storage from logic

### ISSUE THREAD

**Issue by hypervtechnics** [philvessey/NextDepartures#5]
So that you can also use a local storage. E.g. loading in memory from gtfs feed.

**Comment by philvessey** [comment]
Thanks for the suggestion - are you suggesting to just load the data from the csv flat files without the database?

**Comment by hypervtechnics** [comment]
Yeah. If the implementation of data access would be an interface/decoupled. There could be one using the azure sql and one using maybe some plain lists or an advanced solution like [nmemory](https://github.com/zzzprojects/nmemory/).

I'd help. But I am not aware if there is some basic logic contained in e.g. stored procedures/indices which would make it difficult to decouple the parts. And the Feed.cs file has 9900+ lines 🙈  - not that easy to scan through.

**Comment by philvessey** [comment]
I will look at it - it shouldn't be that hard to do actually - i'm just finishing up an example Azure Functions project to automate downloading of feeds and updating the database - I will open source that project too.

**Comment by philvessey** [comment]
I have split Feed.cs so that methods are now in separate files to make code easier to maintain.

**Comment by hypervtechnics** [comment]
Looks good. I will look into it and try to do some refactoring. E.g. the creation of the `Departure `objects like here: https://github.com/philvessey/NextDepartures/blob/master/NextDepartures.Standard/GetServicesByStop.cs#L1776 can be moved to a helper. This alone can save ~900 lines of code. Will make a PR when ready.

For the decoupling: This would only require abstracting the data reader into an interface and separate class at the start of the methods. Or is data dynamically fetched in the middle/end of the methods? E.g. here https://github.com/philvessey/NextDepartures/blob/master/NextDepartures.Standard/GetServicesByStop.cs#L30 up to line 128. 

Also what do you think about making use of the entity classes in https://github.com/itinero/GTFS ?

**Comment by philvessey** [comment]
Good call on the helper methods - I can get started on those today. All of the data is fetched at the start of methods in the using blocks for the SqlConnection.

I will have a look at the entity classes.

**Comment by hypervtechnics** [comment]
Visual Studio might assist you a lot with the refactoring.
Great. So we can replace that part with a call to an interface. I'll look into that today or tomorrow. 

Some entities like Departure do not exist as they are part of your domain. But for the GTFS model everything should be there. And if not: I am currently updating it to match the current GTFS reference.

Also I saw that you are using DateTime.UtcNow. Maybe we can make this configurable. But thats for later :)

**Comment by philvessey** [comment]
If you clone and switch to the dev branch I have created a helper method in Feed.cs to create Departure objects which has cut down on a fair bit of code.

**Comment by hypervtechnics** [comment]
Looks good. For me the build fails because of a missing library TimeZoneConverter which is not missing. Does VS take a while to fully load the project?

Another topic to cut down some code: https://stackoverflow.com/questions/14870478/write-a-well-designed-async-non-async-api/14876375#14876375 Maybe just do the db calls async and make a separate method containing the logic for the data from the db. Or simply only provide the Async API.

Could you add me as a collaborator? Don't want to create fork after fork when I am starting to do some changes. Would be working only on my branch ofc. 😄

**Comment by philvessey** [comment]
Project loads pretty instantly here - I have added you as a collaborator. Is it best practice to only have async methods these days? I notice a lot of libraries have both.

**Comment by hypervtechnics** [comment]
Maybe it is an extension which cant handle this.

I will start working on this tomorrow.

Thank you :)

**Comment by philvessey** [comment]
We should be able to both work from the dev branch - should keep things pretty simple.

**Comment by hypervtechnics** [comment]
So I scanned through the code and have some questions:

- Is there a specific reason for the DataReader and Command being private fields on class level? ^^
- Why don't use the LIMIT keyword in query? Or to be able to totally disable the limit as the order is not related to the distance to the given point?
- What do you think about removing the synchronous methods?

**Comment by philvessey** [comment]
LIMIT isn't in the query as as there are some checks I go through to see if the service is actually running on the said date and time so its easier to just pull all the services linked to a stop and then run the checks to see if actually running. In the code tempDepartures is a collection of all services at that stop and workingDepartures is a collection of the services actually calling at that date and time.

I think I will remove the synchronous methods as at some point I want to add realtime GTFS checking for trip updates too and that requires async calls so it kind of makes sense to remove the old ones. I will update the dev branch today removing them.

**Comment by philvessey** [comment]
Command and DataReader don't need to be private on the class level either - I will update that today too.

**Comment by philvessey** [comment]
The dev branch now has just the async methods and the variables that were not needed at class level are now in the methods.

**Comment by hypervtechnics** [comment]
Hm... Some extension is preventing me from building the library. It's always executing a pending task... And complaining about the TimeZoneConverter dependency.

**Comment by philvessey** [comment]
Strange - builds almost instantly here.

**Comment by hypervtechnics** [comment]
I removed theTimeZoneConverter Nuget package and tried to readd it.

![2019-10-24 18_58_01-NextDepartures - Microsoft Visual Studio](https://user-images.githubusercontent.com/10027956/67507961-4ed7cd80-f690-11e9-9902-dfae16bd70e0.png)

EDIT: I installed 3.1.0 instead of 3.2.0 and it suddenly works now...
EDIT 2: Now I updated to 3.2.0 and now it works. Even git does not detect changes, so the solution/project is in the exact same state. I also deleted the nuget package from local cache.

**Comment by philvessey** [comment]
I'm using Command as a class variable in the database project too - just going through correcting that now - no idea why I did that initially.

**Comment by hypervtechnics** [comment]
Was just asking as sometimes there might be reason to do so.

I am currently creating the abstraction for the data access.

**Comment by hypervtechnics** [comment]
I also moved the model classes out of Feed.cs

One class per file is a good practice as you don't have to search through ^^

**Comment by philvessey** [comment]
Ok - will we get conflicts working on the same branch at once - i'm guessing its fine as long as we both push and sync?

**Comment by hypervtechnics** [comment]
Yeah this should be fine. I will pull the latest changes before pushing so that there should be no conflicts.

**Comment by philvessey** [comment]
Ok - i'm doing the same in the database project with the Model namespace as you have done in the standard project.

**Comment by hypervtechnics** [comment]
Okay. I abstracted the storage access. The details have to be made out. Also there might be some parallelization possible. Could you look over it and tell me if you understand the way I changed your code?

Next steps would be to reduce redundancies through the whole code and reduce the files to less than 500 lines with optimized code 😄 Also making the data model independent from the Database project and the way the sql queries work. Maybe Entity Framework might help here. But seems a bit overkill for now ^^

Also you have to pay attention to the new SqlCommand class as this enables sql injection.

**Comment by philvessey** [comment]
Looks like quite a lot has changed - I will have a look through it tomorrow - do you have Skype in case I have any questions as probably quicker for questions in real time?

**Comment by hypervtechnics** [comment]
You can reach me at my email (`< githubusername > @ gmail.com`). I want to avoid spam ^^. I am reading them very quick or you can reach me at Matrix (use Riot) `@hypervtechnics:matrix.org` for realtime

**Comment by philvessey** [comment]
Ok - don't wait for me to catch up if you want to do some more - i'm a quick study so can look over it all tomorrow.

**Comment by philvessey** [comment]
I'm just looking over the code now to see if I can follow the flow of it - quick question - should the Model folder be renamed to Models or is what we are using considered best practice?

**Comment by hypervtechnics** [comment]
You are right. Models makes more sense ^^

**Comment by philvessey** [comment]
I will change that this evening as going through it all will help me understand it better. I get the general idea that the data retrieval is now independent so in effect the data can be retrieved different ways and then processed for results.

**Comment by hypervtechnics** [comment]
Yeah this enables you to both easily switch databae or just load from the local file system. For the logic itself to enhance/optimize it I first need to understand it. Could you add some comments to the GetDepartures* methods to understand it or explain it? Is it still working with the newest standard?

**Comment by philvessey** [comment]
I will test it this evening / weekend once I have gone over it all as I have some spare time. Will make sure the methods are documented so you can follow it. I will reach out once I have pushed to the dev branch with some comments in.

**Comment by philvessey** [comment]
Im looking at doing some tests but im confused what I should be passing into the feed class. Before it was new Feed(connectionString), im guessing now it should be new Feed(new SqlStorage(connectionString)) but NextDepartures.Storage.SqlServer isn't referenced from the Standard project - should it be?

**Comment by hypervtechnics** [comment]
The intent behind this it that only the necessary dependencies are used by the user of the library. This means if the user wants to have the feed loaded from the local filesystem he has no use for the SqlClient. The project consuming the library can reference the SqlStorage package directly. The Standard project would then be added implictly because SqlStorage depends on Standard. Or you could reference both. Hope it helped :)

**Comment by hypervtechnics** [comment]
For your question: the Standard contains the logic. The logic is consumed by another library/application (referencing above applies). So the Standard library should not have a dependency to SqlStorage. The second initialization  is correct and would need to be done in a third project referencing both the standard and sqlstorage project

**Comment by philvessey** [comment]
Ok I think I understand - so the Storage library for SqlServer and any others we create need to go up to NuGet too when this is completed?

**Comment by hypervtechnics** [comment]
Exactly :)

**Comment by philvessey** [comment]
Ok great :) I will finish up documenting methods tomorrow and do some testing. I will let you know once I have done that so you can have a look through.

**Comment by philvessey** [comment]
Testing looks ok - I cant see any issues with the data being returned so far. I am about 50% through documenting all the methods so will push the repo tomorrow once I am finished with them.

**Comment by philvessey** [comment]
If you pull the dev branch now you will get the latest changes. I have added some comments to explain how the processing works and why. Do you have any experience of working with GTFS and local flat files / Azure Storage flat files - its easy enough to extract data from CSV as I do this in the database project and i'm guessing you can use LINQ somehow to format the results in the same way the SQL queries do?

**Comment by hypervtechnics** [comment]
I worked a lot with local GTFS files which are basically just CSV files. Not anything related to Azure unfortunately. Now you can just implement your own IDataStorage using the local files as a data source without messing with the logic itself.

I will look into the logic the next days.

**Comment by philvessey** [comment]
Do you have any examples of joining data from lists using LINQ - similar to how SQL lets you do LEFT JOIN etc. If I have the data from CSV files in their own lists e.g. agencies, calendars etc

**Comment by hypervtechnics** [comment]
This may be interesting for you: https://docs.microsoft.com/de-de/dotnet/csharp/linq/perform-left-outer-joins

**Comment by philvessey** [comment]
Yea that looks like the right sort of thing - I'm keen to give people using the library on a server the option to pull from azure storage also instead of a SQL database as storage is cheaper and it just means dropping a GTFS zip into a storage blob

**Comment by hypervtechnics** [comment]
Yeah. By abstracting it everyone can include their own data storage. But would be cool to have some out-of-the-box ones I guess. Anyway: I am wondering why step 6 and 9 are the same, therefore evaluated twice. Also the logic seems to duplicate in a lot of places. Maybe we can start optimizing there.

My suggestions:

1. Remove duplicates in logical part and reuse more code
2. Remove duplicate processing steps in if statements to reduce redundant calculations

**Comment by philvessey** [comment]
They are not evaluated twice, step 6 runs if we know what day the service runs on - step 9 runs if we have no idea what day it runs on and having to check exceptions to see if it is running.

I agree there is probably room for improvement that will reduce lines of code.

**Comment by hypervtechnics** [comment]
I just pushed some refactoring for the database project. I will take a look at the logic during the next days.

**Comment by philvessey** [comment]
I will take a look :)

**Comment by philvessey** [comment]
Looks good - certainly makes the code easier to read / look at. I have pushed another commit updating the packages as CsvHelper has put out a new version.

**Comment by hypervtechnics** [comment]
I just pushed new changes with a little refactoring for the database project.

**Comment by philvessey** [comment]
I have also added some console output to the database project to show progress - instead of just looking at a blinking cursor wondering how far is left to go.

**Comment by hypervtechnics** [comment]
I just pushed some more refactoring for the database project.

**Comment by hypervtechnics** [comment]
I did some more refactoring for the database project. Now the Program.cs is at ~280 lines which is a lot more readable regarding the ~980 lines from the beginning. The current way is a good way 👍.

I am looking at the standard project and started doing some refactoring. Do you want to use LINQ or not? That would simplify a lot.

Also what do you think about implementing some kind of cache for the data as refetching all data is quite resource hungry. We can supply a decorator for the IDataStorage (later).

**Comment by philvessey** [comment]
Have you pushed the changes as Program.cs is showing 399 lines for me?
No issues with using LINQ - i'm all for it if it leads to improvements.
I think caching would be a good idea too - was thinking if I make an azure storage extension you don't really want to be pulling down CSV files each time an endpoint is used so would certainly need to be able to cache at that point and maybe pull data from source once every x hours etc.

**Comment by philvessey** [comment]
This evening I am creating new agencies endpoints for people to query - I will push those either later tonight or in the morning.

**Comment by hypervtechnics** [comment]
Sorry I forgot to commit & push. I did that now. As said I just started refactoring at the toppings of both files. They have a resembling logic. I will see what I can do. 
Also regarding caching: This that can be cached are just the Get*Async() methods which do not require a parameter. I will implement that tomorrow.

**Comment by philvessey** [comment]
Did you pull the dev branch at all in the last 30 minutes? - I made a mistake that I have undone but if you pulled you might have got the changes - im fixing now and will push up once corrected.

**Comment by philvessey** [comment]
Just pushed the changes I made to the dev branch. There is now new agencies endpoints for people to query.

**Comment by philvessey** [comment]
While you are looking at the refactor and caching I have started to add the other GTFS tables that were not included in the database project should that data but used by the library at a later date.

**Comment by hypervtechnics** [comment]
I dont think thats necessary for the library. If you take a look at this library: https://github.com/itinero/GTFS a lot of work has been done automatically. Like normalizing and stuff. The queries can be done directly on the IDataStorage as the Feed class does no real work with the data. In the long term I think that the IDataStorage should be fetching the data via GTFS library and leave the querying up to the user.

Currently on the train. Sorry if it sounds confusing.

**Comment by philvessey** [comment]
The data needs to be in the database to query first though? I'm just making the database project parse all the GTFS feed into the database and not just certain tables from it.

**Comment by hypervtechnics** [comment]
For the parsing the gtfs library may be used as it is also more flexible. For querying either the IDataStorage may be used or the gtfs library. This library should really just do the logic part regarding service calculation I think.

If you don't agree I think at least the query operations (which are just handing from Feed.cs to IDataStorage) should be removed from Feed.cs as the dev using ND.S is in control of the data storage and can execute the queries there instead.

**Comment by hypervtechnics** [comment]
In addition: in GetServicesByStopAsync you do several `if (workingDepartures.Count < count)` and `workingDepartures = workingDepartures.Take(count).ToList();` which are wrong imo. The first `Take` I understand. But all of the `if` conditions are unnecessary to me. And also: Shouldn't the `if` conditions be `<=` as the preceding `Take` will take care.

EDIT: Ah I see you add more stops between the `Take` operations. But the first if is unnecessary imo and the other if's require a change to `<=`.

EDIT 2: The other two `if` conditions are unnecessary too as there was the `Take` before and this ensures there are not more than `count` items in the list.

EDIT 3: For later: maybe add Count for the ByTrip method too? Again: Just say yes and I will apply the same principal as in ByStop to avoid mc.

EDIT 4: I did both for testing. Then a question: Why 12 hours for the trip and 1 hour for the stop?

Do you agree? If yes, please just tell me as I already changed a lot of the code and want to prevent merge conflicts.

**Comment by philvessey** [comment]
I’ll run over each point.

1. For the stop endpoint I wanted it initially to show no more than an hour ahead - we can change this though as some stops can have long wait between services.

2. On the trip endpoint I haven’t used Take as I wanted to show every stop a trip calls at and some journeys have a lot more than 10 stops etc. I did the 12 hours as some trip data I was using was showing repeated services over different days but not sure if that was an issue with the data.

The takes are there multiple times as if it checks today’s services and there is already 10 then we don’t need to process tomorrow’s data at all - it saved on processing time basically.

I don’t think we will have any merge conflicts as I haven’t touched the stop or trip endpoints since you started your refactor so we should be ok - happy to take a look at what you have done as the rest of your code is good quality and cut down on quite a lot of lines.

**Comment by philvessey** [comment]
> For the parsing the gtfs library may be used as it is also more flexible. For querying either the IDataStorage may be used or the gtfs library. This library should really just do the logic part regarding service calculation I think.
> 
> If you don't agree I think at least the query operations (which are just handing from Feed.cs to IDataStorage) should be removed from Feed.cs as the dev using ND.S is in control of the data storage and can execute the queries there instead.

With this are you saying we wouldn’t need any endpoints at all essentially?

Think we should finish the refactor of stop and trip and then branch out to different issues to look at other things. I’m open to any and all suggestions really.

**Comment by philvessey** [comment]
I can see you are doing things on a refactor branch - I can merge the dev branch into master tomorrow once I have finished some changes to the Database project - don’t think conflicts will be a problem as I haven’t touched the ND.S code since adding the agencies endpoints.

**Comment by hypervtechnics** [comment]
>     For the stop endpoint I wanted it initially to show no more than an hour ahead

I will move that one to a variable so we can make the user able to change that later.

>     show every stop a trip calls

Ah okay seems logical. I will keep this in mind. 😄 

> we wouldn’t need any endpoints at all essentially

We need those endpoint. But this library is not the place for this, I think. It is better to be implemented with a library specialized to work with the GTFS data. The [linked library](https://github.com/itinero/GTFS) is such a library. 
If your use case is to use a sql server storage I think its better to implement the data storage interface as a plugin of the gtfs lib. You may follow this implementation which is for SQLite: https://github.com/itinero/GTFS/tree/develop/src/GTFS.DB.SQLite 
This library would then only need to reference a data storage using the GTFS lib which then implements the different storages.

> finish the refactor of stop and trip and then branch out to different issues

Good idea. We can go through this thread and search for the word `later` 😆 ...

> doing things on a refactor branch

Yeah I moved over to a refactoring branch, as I only assumed things and didn't want to break anything. I'd wait with merging back into master. Do you have CI?

**Comment by philvessey** [comment]
No I don’t have CI up and running yet - it’s on my list to setup - I’m away from the computer today but I can see you have a pull request to merge into dev - let me know when you are ready for that and I can merge in.

**Comment by hypervtechnics** [comment]
So... I did the big refactoring. From ~2500 lines to ~350 🎉 🎈 . Will push it now. I also implemented the preloading of agencies, stops and exceptions as they are required independently from the parameters. I changed to a small factory which changed the initialization method. I wrote down some TODOs for later as I don't know if the logic allows implementing some of the TODOs (like datetime now to customizable). I renamed a lot to be more clear. Maybe I will rerefactor a bit but currently I am very happy with the code (if it works 😝).

Could you test the logic with a dataset? (Best would be before and after the change and compare the results)

**Comment by philvessey** [comment]
I’ll do some testing Friday when I’m back at home as I’m off work all day so will report back with any issues if there are any :)

**Comment by philvessey** [comment]
Starting to have a look through the refactoring branch now.

**Comment by hypervtechnics** [comment]
Things are done and now every point should be opened as an issue to get a better overview :)

**Comment by philvessey** [comment]
I'm spending the day today documenting the new methods. Once complete I will merge into master and think about some of the new issues that have been discussed.

**Comment by philvessey** [comment]
I have had a quick look through and created some new issues. I have pushed into master and created a new dev branch bumping the version number to 1.2.1. Good news - the build pipeline works perfectly and is pushing successfully up to NuGet when master gets new commits.
