### ISSUE TITLE
Replace UtcNow

### ISSUE THREAD

**Issue by philvessey** [philvessey/NextDepartures#9]
Replace UtcNow to a time settable by the user so they can request services at a time point of their choice.

**Comment by philvessey** [comment]
Im going to look at this over the next couple of days - figuring its best to pass a DateTime object into the endpoints instead of hard coding UtcNow. That way a user can pass in any DateTime object to look at departures from any date / time.

**Comment by philvessey** [comment]
I have completed the code changes for this feature - will test over the next day and then commit.

**Comment by hypervtechnics** [comment]
I am currently thinking about passing a dedicated object for the settings.

Meaning the call would look something like that:

`feed.GetServices*Async("", new ServiceOptions() { Time = DateTime.UtcNow });`

**Comment by philvessey** [comment]
I can check in what I have providing it tests OK tomorrow and we can go that route if need be.

**Comment by philvessey** [comment]
> I am currently thinking about passing a dedicated object for the settings.
> 
> Meaning the call would look something like that:
> 
> `feed.GetServices*Async("", new ServiceOptions() { Time = DateTime.UtcNow });`

Is there an advantage to this instead of just passing in arguments?

**Comment by hypervtechnics** [comment]
Not yet. I don't know if we will have more options at a later point. But for now we can keep it as a simple parameter.

**Comment by philvessey** [comment]
I have done some research on NodaTime today and that looks a better option to handle time zones as it will work correctly on any OS - im going to check in my changes to dev tonight and work on a NodaTime conversion tomorrow on a separate branch.

**Comment by philvessey** [comment]
Close with commit 8a75607d03ee010db247ea0005c2768b62fb0188.

**Comment by hypervtechnics** [comment]
Added another commit. Is `DateTime.Now` or `DateTime.UtcNow` correct?

**Comment by philvessey** [comment]
DateTime.Now is correct - it doesnt need to be DateTime.UtcNow now the user can set own.

**Comment by hypervtechnics** [comment]
Yeah but to keep current code compatible we should still offer the old method signature. Also if the user does not care about the datetime or wants it to be now he can just omit the value :)

**Comment by hypervtechnics** [comment]
Fixed.

**Comment by philvessey** [comment]
Agreed overloading is a better idea. Think we can close this one now.
